# Example credentials file structure for cloud integrations
# Copy this structure to your encrypted credentials file using: rails credentials:edit

# smtp:
#   user_name: my-smtp-user
#   password: my-smtp-password
#
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Cloud service API credentials
google:
  client_id: your_google_client_id_here
  client_secret: your_google_client_secret_here

dropbox:
  client_id: your_dropbox_client_id_here
  client_secret: your_dropbox_client_secret_here

notion:
  client_id: your_notion_client_id_here
  client_secret: your_notion_client_secret_here

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: d7dabf9f8b824b73fb717929bb6a0d71dc27b885a56b02e14919cc8fd5ff74b5f0e499371380a759c1e94d0d319b21d6f6bd598bab76959a0a29fb8a310612be