global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "claude_code_creators_rules.yml"

scrape_configs:
  - job_name: 'claude-code-creators'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    headers:
      Authorization: "Bearer <%= ENV['METRICS_TOKEN'] %>"

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093